FROM python:3.11-alpine

# 安装 debugpy 用于调试支持
RUN pip install --no-cache-dir debugpy

RUN adduser -D func || true

WORKDIR /app

COPY runtime-python.py /app/runtime.py

USER func

ENTRYPOINT ["python3", "/app/runtime.py"]
